### ISSUE TITLE
Functional issues with the library (PBP 0.2 BETA)

### ISSUE THREAD

**Issue by Q99kek** [ProjectBlackPearl/project_black_pearl#19] opened 2023-01-14 12:31 UTC
1. It seems unable to run exec files that are set to be run as admin only UNLESS you also run the pbp app as admin. I don't know if this is intended or not, but if is it should be clarified somewhere. If it's not, I guess solving it could be done by either requiring pbp to be run as admin or by somehow making it capable of opening those exec files.

2. When you try to edit a game in your library and click "Done", it automatically closes the app and doesn't even save your edit. Clicking off after editing to avoid the app closing doesn't work either so there's no way to save an edit right now.

**Comment by infinity-plus** [comment] 2023-01-14 12:32
Point 1 seems to be pretty clear.
Point 2 we need to test.

Can you tell me what exactly you edited?

**Comment by Q99kek** [comment] 2023-01-14 12:40
It seems to happen with everything I edit. However, this bug doesn't affect everything. As far as I can tell it's only affecting games with execs that need to be run as admin.

**Comment by zun1uwu** [comment] 2023-01-14 15:13
Please run PBP through cmd.exe or another shell and provide the output after it closes.

**Comment by infinity-plus** [comment] 2023-01-14 15:16
>  it's only affecting games with execs that need to be run as admin.

I cannot reproduce the issue as I do not have any games that require to be run as admin. We could add an option to run as admin if we figure out the way to know which games have these requirements.

**Comment by Brisolo32** [comment] 2023-04-05 20:21
It's been some time since the last comment on this issue. Is it still present @Q99kek?

**Comment by Q99kek** [comment] 2023-04-08 18:48
Yeah. Editing games with execs that need to be run as admin doesn't work at all and the app just closes whenever I try, regardless if I run PBP itself as admin or not. Running games with admin execs only works if I also run PBP as admin. Unsure of what's causing it to not work, tried running it through cmd but it gives no output after it closes

**Comment by infinity-plus** [comment] 2023-04-21 03:54
Since the issue is partially fixed, closing this in favour of specific issue #41

**Closed by infinity-plus** 2023-04-21 03:54 UTC
Labels: bug
